# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
xcode_project: Example/LFRouterExample.xcodeproj # path to your xcodeproj folder
xcode_scheme: LFRouterExample
xcode_sdk: iphonesimulator11.4